name: fleet_admin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^1.0.0
  intl: ^0.17.0
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0 
  flutter_phone_direct_caller: ^2.1.1
  flutter_svg: ^1.1.5
  flutter_typeahead: ^4.1.1
  provider: ^6.0.4
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+6
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  syncfusion_flutter_charts: ^20.4.49
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/svg/
    - assets/images/png/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

